"""ReconForge reporting package.

Responsibilities:
- Converts PipelineResult into human-readable or machine-readable artifacts
- Produces statistics, timeline, JSON, Markdown, and HTML reports
- References artifacts generated by plugins (e.g. screenshots)
"""
